import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { judge, proseLines, rewrap, LIMIT } from '../scripts/lib/line-length.mjs';

const long = (n) => 'word '.repeat(Math.ceil(n / 5)).slice(0, n);

test('a page whose prose is within the column is held to it', () => {
  const page = ['# Title', '', ...Array(6).fill('a short line of prose here')].join('\n');
  assert.equal(judge(page).wrapped, true);
  assert.equal(judge(page).over.length, 0);
});

test('one drifted line on an otherwise wrapped page is reported', () => {
  const page = ['# Title', '', ...Array(20).fill('a short line of prose here'), '', long(140)].join('\n');
  const verdict = judge(page);
  assert.equal(verdict.wrapped, true);
  assert.equal(verdict.over.length, 1);
  assert.equal(verdict.over[0].length, 140);
});

test('a page that is not wrapped at all is left alone', () => {
  const page = ['# Title', '', ...Array(6).fill(long(140))].join('\n');
  assert.equal(judge(page).wrapped, false);
  assert.equal(judge(page).over.length, 0);
});

test('code, tables, html and frontmatter are not prose', () => {
  const page = [
    '---', `description: ${long(140)}`, '---',
    '# Title', '',
    '```abap', long(140), '```', '',
    `| a | ${long(140)} |`, '',
    `<div title="${long(140)}">`, '',
    'real prose',
  ].join('\n');
  assert.deepEqual(proseLines(page).map((l) => l.text), ['real prose']);
});

test('a generated block is not this gate\'s business', () => {
  const page = [
    '# Title', '',
    '<!-- samples:start (generated by scripts/link-samples.mjs — do not edit) -->',
    long(140),
    '<!-- samples:end -->', '',
    'real prose',
  ].join('\n');
  assert.deepEqual(proseLines(page).map((l) => l.text), ['real prose']);
});

test('an image and the caption that repeats its alt text are exempt', () => {
  const alt = long(120);
  const page = ['# Title', '', `![${alt}](/x.svg)`, '', `*${alt}*`, '', 'real prose'].join('\n');
  assert.deepEqual(proseLines(page).map((l) => l.text), ['real prose']);
});

test('an italic line that is NOT the alt text is prose like any other', () => {
  const page = ['# Title', '', '![short alt](/x.svg)', '', `*${long(120)}*`, '', 'real prose'].join('\n');
  assert.equal(proseLines(page).length, 2);
});

test('a line that is only long because of one URL is exempt', () => {
  const url = `https://example.com/${'a'.repeat(120)}`;
  const page = ['# Title', '', `See ${url}`, '', 'real prose'].join('\n');
  assert.deepEqual(proseLines(page).map((l) => l.text), ['real prose']);
});

test('rewrap changes whitespace and nothing else', () => {
  const source = `# Title\n\n${long(140)}\n`;
  const out = rewrap(source, [3]);
  assert.notEqual(out, null);
  assert.equal(out.replace(/\s+/g, ' ').trim(), source.replace(/\s+/g, ' ').trim());
  for (const line of out.split('\n')) assert.ok(line.length <= LIMIT, line);
});

test('rewrap never splits a code span, a link or a container directive', () => {
  const source = [
    '# Title', '',
    '::: tip **Naming**',
    `Use ${'x '.repeat(30)}\`ele( )\` and [the sample catalog](https://example.com/a/b) here.`,
    ':::', '',
  ].join('\n');
  const out = rewrap(source, [4]);
  const lines = out.split('\n');
  // the directive lines still stand alone
  assert.ok(lines.includes('::: tip **Naming**'));
  assert.ok(lines.includes(':::'));
  // and nothing was broken in the middle
  assert.ok(out.includes('`ele( )`'));
  assert.ok(out.includes('[the sample catalog](https://example.com/a/b)'));
});

test('the manual itself passes the rule it sets', async () => {
  const { glob } = await import('node:fs/promises');
  let held = 0;
  const over = [];
  for await (const file of glob('docs/**/*.md')) {
    if (file.startsWith('docs/public/') || file.includes('/.vitepress/')) continue;
    const verdict = judge(await readFile(file, 'utf8'));
    if (!verdict.wrapped) continue;
    held++;
    for (const line of verdict.over) over.push(`${file}:${line.line} (${line.length})`);
  }
  assert.ok(held > 40, `only ${held} page(s) counted as wrapped`);
  assert.deepEqual(over, []);
});
