import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { manualPages } from '../scripts/lib/prose.mjs';
import { findUnknown, projectWords } from '../scripts/lib/vocabulary.mjs';

const unknown = (markdown, words = []) => findUnknown(markdown, { words }).map((f) => f.word);
const page = (body) => `# Title\n\n${body}\n`;

test('the four typos that reached the published site are caught', () => {
  /* Two hand edits, two days, one page - and all fourteen other gates green.
     This is the case the gate exists for. */
  assert.deepEqual(
    unknown(page('To use a framework, you always havte to fullfll certain requoirememnts.')),
    ['havte', 'fullfll', 'requoirememnts'],
  );
  assert.deepEqual(unknown(page('that can be a structure, thant can be another.')), ['thant']);
});

test('ordinary English is not reported', () => {
  assert.deepEqual(unknown(page('To use a framework, you always have to fulfill certain requirements.')), []);
});

test('an identifier is not a word to be spelled', () => {
  assert.deepEqual(unknown(page('abap2UI5 calls z2ui5_if_app and the liveChange wire, per the ICF and its APIs.')), []);
});

test('a name with a letter outside A-Z is one token', () => {
  /* [A-Za-z] starts a new token at the "ller" of "Müller" and reports it. */
  assert.deepEqual(unknown(page('edited by Müller'), ['müller']), []);
  assert.deepEqual(unknown(page('edited by Müller')), ['Müller']);
});

test('emphasis inside a word does not split it', () => {
  /* `**f**rontend` renders as one word and has to be read as one. Reported
     as "frontend" (which the project list carries) and never as "rontend". */
  assert.deepEqual(unknown(page('The UI5 **f**rontend, embedded as constants.')), ['frontend']);
  assert.deepEqual(unknown(page('The UI5 **f**rontend, embedded as constants.'), ['frontend']), []);
});

test('a hyphenated compound is judged part by part', () => {
  assert.deepEqual(unknown(page('a design-time artifact and a runtime-typed model'), ['typed']), []);
  assert.deepEqual(unknown(page('a design-tyme artifact')), ['tyme']);
});

test('code, link targets and generated blocks are not prose', () => {
  const body = [
    '```abap', 'DATA(havte) = fullfll.', '```', '',
    'See `zcl_havte_fullfll` and [the page](/advanced/havte-fullfll).', '',
    '<!-- samples:start (generated by scripts/link-samples.mjs — do not edit) -->',
    'havte fullfll requoirememnts',
    '<!-- samples:end -->',
  ].join('\n');
  assert.deepEqual(unknown(page(body)), []);
});

test('a project word is known through the list, and the list is read', () => {
  assert.deepEqual(unknown(page('one roundtrip per click'), ['roundtrip']), []);
  assert.deepEqual(unknown(page('one roundtrip per click')), ['roundtrip']);
  assert.ok(projectWords().length > 100, 'vocabulary.txt carries the project words');
  assert.ok(projectWords().includes('roundtrip'));
});

test('every prose word of the manual is one something knows', () => {
  const words = projectWords();
  const found = [];
  for (const file of manualPages('docs')) {
    for (const f of findUnknown(readFileSync(file, 'utf8'), { words })) {
      found.push(`${file}:${f.line} ${f.word}`);
    }
  }
  assert.deepEqual(found, []);
});
