/* The words of a page that are PROSE - what a reader reads, as opposed to
 * what a compiler or a browser reads - and the house spelling of them.
 *
 * Fenced code, inline code, link targets, HTML tags and comments, bare URLs,
 * generated blocks and the frontmatter (all but its title and description,
 * which a search result shows) are blanked out, character for character, so a
 * match in what
 * comes back sits at the same offset in the original line: a spelling can be
 * checked, or corrected, without ever touching an ABAP keyword, a CSS property
 * or a path.
 *
 * Shared by test/spelling.test.mjs, which is the gate, and by
 * scripts/fix-spelling.mjs, which rewrites a page towards the rule. */

import { readdirSync } from 'node:fs';
import { join } from 'node:path';

/** Every page of the manual under `docs/`: not `public` (a generated copy of
 *  each page) and not a dot-directory (`.vitepress`, with the build in it). */
export const manualPages = (dir) => readdirSync(dir, { withFileTypes: true }).flatMap((e) =>
  e.isDirectory() ? (e.name === 'public' || e.name.startsWith('.') ? [] : manualPages(join(dir, e.name)))
    : e.name.endsWith('.md') ? [join(dir, e.name)] : []);

const blank = (s) => ' '.repeat(s.length);

/** Each line of `markdown` with everything that is not prose replaced by
 *  spaces of the same length. */
export function proseLines(markdown) {
  const lines = markdown.split('\n');
  const out = [];
  let fence = null;
  let comment = false;
  let generated = false;
  let front = lines[0] === '---' ? 'open' : null;
  for (const line of lines) {
    /* A block a generator wrote - the API reference out of z2ui5_if_client,
       the Working Samples out of a catalog - is that generator's to spell:
       a correction here would be undone by its next run, or fail its
       freshness gate. The markers are the generators' own. */
    if (generated) {
      out.push(blank(line));
      if (/^<!-- \w+:end -->/.test(line)) generated = false;
      continue;
    }
    if (/^<!-- \w+:start \(generated by /.test(line)) {
      out.push(blank(line));
      generated = true;
      continue;
    }
    if (front === 'open') {
      /* The title and the description are what a search result and a preview
         card show, and a reader reads them; the rest of the frontmatter is
         configuration. */
      const shown = line.match(/^(title|description):\s*/);
      out.push(shown ? blank(shown[0]) + line.slice(shown[0].length) : blank(line));
      if (line === '---' && out.length > 1) front = 'closed';
      continue;
    }
    const opening = line.match(/^\s*(`{3,}|~{3,})/);
    if (fence) {
      out.push(blank(line));
      if (opening && opening[1][0] === fence[0] && opening[1].length >= fence.length) fence = null;
      continue;
    }
    if (opening) {
      fence = opening[1];
      out.push(blank(line));
      continue;
    }
    /* An HTML comment that runs over several lines: a maintainer's note, and
       one that may quote the very code the rule must not touch. */
    let text = line;
    if (comment) {
      const close = text.indexOf('-->');
      if (close === -1) { out.push(blank(text)); continue; }
      text = blank(text.slice(0, close + 3)) + text.slice(close + 3);
      comment = false;
    }
    text = text.replace(/<!--[\s\S]*?-->/g, blank);
    const open = text.indexOf('<!--');
    if (open !== -1) { text = text.slice(0, open) + blank(text.slice(open)); comment = true; }
    out.push(text
      .replace(/`[^`]*`/g, blank)
      .replace(/\]\([^)]*\)/g, blank)
      .replace(/<[^>]+>/g, blank)
      .replace(/https?:\/\/\S+/g, blank));
  }
  return out;
}

/* ---- the house spelling -----------------------------------------------
 *
 * American. The manual is read by people whose systems are SAP's, and SAP
 * writes "authorization", "Customizing", "behavior definition" and "catalog";
 * a manual that spelled its own prose the other way would teach a reader to
 * search for words their system does not use. It was mixed for years - 15
 * behaviours against 39 behaviors, in the same chapter sometimes - which is
 * what makes a rule worth a test: a decision that lives only in a document
 * wanders back the next time somebody pastes a paragraph.
 *
 * Each rule is a pattern and the American form of what it matched. The
 * patterns are the BRITISH forms, because that is the direction the drift
 * runs; `-ise` and `-isation` are matched in general with the words that are
 * `-ise` in both spellings listed out, and a word this list has not met is
 * reported rather than passed - the message names it, and the list is where
 * to add it. */

const keepCase = (like, word) => {
  if (!word) return word;
  if (like === like.toUpperCase() && like.length > 1) return word.toUpperCase();
  if (like[0] === like[0].toUpperCase()) return word[0].toUpperCase() + word.slice(1);
  return word;
};
/* The tail of a word replaced, in the case the tail was written in. */
const tailed = (re, map) => (w) => w.replace(re, (t) => keepCase(t, map[t.toLowerCase()]));
const mapped = (map) => (w) => keepCase(w, map[w.toLowerCase()]);
const exact = (map) => [
  new RegExp(`\\b(?:${Object.keys(map).join('|')})\\b`, 'gi'),
  mapped(map),
];

/* Words that end in -ise in American English too, as the stem before "is":
   "surpr" for surprise, "prom" for promise. Some are the whole stem (rise,
   arise, disable, crises), some its end (unsurprised, disenfranchise), and
   four families go by the stem's last letter - ...wise, ...aise, ...oise,
   ...uise - because no British verb lives there. */
const ISE_IN_BOTH = (stem) =>
  /^(?:r|ar|d|v|cr|el|ir|upr|sunr|moonr|exorc|circumc|telev|superv|inc|exc|conc|prec|dem|mort|val|chem|cer|an|treat|parad|expert|chast|desp)$/i.test(stem)
  || /(?:prom|prem|adv|advert|rev|dev|exerc|franch|merchand|comprom|improv|surpr|compr|enterpr|repr|appr|surm)$|[waou]$/i.test(stem);

export const BRITISH = [
  [/\b(?:licenc)(e|es|ed|ing)\b/gi, (w) => w.replace(/c(e|es|ed|ing)$/i, (t) => keepCase(t, 's' + t.slice(1).toLowerCase()))],
  [/\bpractis(e|es|ed|ing)\b/gi, tailed(/is(e|es|ed|ing)$/i, { ise: 'ice', ises: 'ices', ised: 'iced', ising: 'icing' })],
  exact({
    grey: 'gray', greys: 'grays', greyed: 'grayed', greying: 'graying',
    artefact: 'artifact', artefacts: 'artifacts',
    whilst: 'while', amongst: 'among',
    learnt: 'learned', spelt: 'spelled', dreamt: 'dreamed', spoilt: 'spoiled',
    programme: 'program', programmes: 'programs',
    defence: 'defense', defences: 'defenses', offence: 'offense', offences: 'offenses', pretence: 'pretense',
    enquire: 'inquire', enquires: 'inquires', enquired: 'inquired', enquiring: 'inquiring', enquiry: 'inquiry', enquiries: 'inquiries',
    cheque: 'check', cheques: 'checks', tyre: 'tire', tyres: 'tires',
    mould: 'mold', moulds: 'molds', moulded: 'molded', moulding: 'molding',
    storey: 'story', storeys: 'stories',
    sceptic: 'skeptic', sceptics: 'skeptics', sceptical: 'skeptical', scepticism: 'skepticism',
    aluminium: 'aluminum', maths: 'math', ageing: 'aging',
    judgement: 'judgment', judgements: 'judgments', acknowledgement: 'acknowledgment', acknowledgements: 'acknowledgments',
    sizeable: 'sizable', likeable: 'likable', moveable: 'movable', cosy: 'cozy',
    pyjamas: 'pajamas', aeroplane: 'airplane', aeroplanes: 'airplanes',
    plough: 'plow', ploughs: 'plows', kerb: 'curb', kerbs: 'curbs', draught: 'draft', draughts: 'drafts',
    jewellery: 'jewelry', speciality: 'specialty', specialities: 'specialties', orientated: 'oriented',
    encyclopaedia: 'encyclopedia', manoeuvre: 'maneuver', manoeuvres: 'maneuvers', manoeuvred: 'maneuvered', manoeuvring: 'maneuvering',
    sulphur: 'sulfur', paediatric: 'pediatric', anaemia: 'anemia', anaemic: 'anemic', oestrogen: 'estrogen', aeon: 'eon', aeons: 'eons',
    focussed: 'focused', focussing: 'focusing',
    enrol: 'enroll', enrols: 'enrolls', enrolment: 'enrollment', enrolments: 'enrollments',
    fulfil: 'fulfill', fulfils: 'fulfills', fulfilment: 'fulfillment',
    instalment: 'installment', instalments: 'installments',
    skilful: 'skillful', skilfully: 'skillfully', wilful: 'willful', wilfully: 'willfully', instil: 'instill', distil: 'distill',
  }),
  [/\bper cent\b/gi, (w) => keepCase(w, 'percent')],
  [/\bco-op(erat\w*)\b/gi, (w) => w.replace(/-/, '')],
  [/\bco-ord(inat\w*)\b/gi, (w) => w.replace(/-/, '')],

  /* -our. Not anchored at the front, so recolour and discolour count too. */
  [/(?:behavi|col|flav|hon|lab|fav|neighb|rum|hum|arm|harb|od|sav|savi|vap|endeav|rig|vig|val|cand|clam|ferv|splend|tum|parl|demean|ard)our[a-z]*/gi,
    (w) => w.replace(/our/i, (m) => (m === 'OUR' ? 'OR' : 'or'))],
  /* -ogue */
  [/\b(?:catalogu|dialogu|analogu)(e|es|ed|ing)\b/gi, tailed(/u(e|es|ed|ing)$/i, { ue: '', ues: 's', ued: 'ed', uing: 'ing' })],
  /* -re */
  [/\b(?:cent|met|lit|fib|theat|calib|somb|spect|lust|sab|meag|och|scept|kilomet|millimet|centimet)r(e|es|ed|ing)\b/gi,
    tailed(/r(e|es|ed|ing)$/i, { re: 'er', res: 'ers', red: 'ered', ring: 'ering' })],
  /* one l, where British doubles it on an unstressed syllable */
  [/\b(?:label|level|signal|travel|model|cancel|channel|tunnel|dial|equal|initial|marshal|total|fuel|quarrel|counsel|panel|pedal|pencil|rival|shovel|spiral|tassel|jewel|grovel|revel|shrivel|snivel|swivel|ravel|unravel|funnel|kennel|libel|parcel|barrel|cudgel|duel|enamel|gambol|gravel|hovel|imperil|remodel|relabel|refuel|bevel|carol|chisel|cavil|devil|drivel|medal|metal|nickel|pummel|stencil|tinsel|trowel|yodel|marvel|wool)l(ed|ing|ers?|ors?|ous|en)\b/gi,
    (w) => w.replace(/ll/i, (m) => m[0])],
  /* -yse - not "-yses", which is also the plural of analysis */
  [/\b[a-z]+lys(e|ed|ing|ers?)\b/gi, (w) => w.replace(/s(e|ed|ing|ers?)$/i, (t) => keepCase(t, 'z' + t.slice(1).toLowerCase()))],
  /* -isation, -ise: general, with the words that are -ise in both listed */
  [/\b([a-z]+)isations?\b/gi, (w) => w.replace(/isation/i, (m) => keepCase(m, 'ization')), (stem) => !/^improv$/i.test(stem)],
  [/\b([a-z]+)is(e|es|ed|ing|ers?|abl[ey])\b/gi,
    (w) => w.replace(/is(?=(?:e|es|ed|ing|ers?|abl[ey])$)/i, (m) => keepCase(m, 'iz')), (stem) => !ISE_IN_BOTH(stem)],
];

/** Every British spelling in the prose of `markdown`: line and column
 *  (1-based), the word, and the American form. */
export function findBritish(markdown) {
  const found = [];
  proseLines(markdown).forEach((line, i) => {
    const taken = [];
    const free = (a, b) => !taken.some(([s, e]) => a < e && b > s);
    for (const [re, american, stemIs] of BRITISH) {
      for (const m of line.matchAll(re)) {
        const [start, end] = [m.index, m.index + m[0].length];
        if (!free(start, end)) continue;
        if (stemIs && !stemIs(m[1])) continue;
        taken.push([start, end]);
        found.push({ line: i + 1, col: start + 1, word: m[0], american: american(m[0]) });
      }
    }
  });
  return found.sort((a, b) => a.line - b.line || a.col - b.col);
}

/** `markdown` with every British spelling in its prose replaced - and only
 *  there: the offsets come from the blanked lines and are applied to the
 *  original ones. */
export function americanize(markdown) {
  const lines = markdown.split('\n');
  const hits = findBritish(markdown);
  for (let k = hits.length - 1; k >= 0; k--) {
    const { line, col, word, american } = hits[k];
    const at = lines[line - 1];
    lines[line - 1] = at.slice(0, col - 1) + american + at.slice(col - 1 + word.length);
  }
  return lines.join('\n');
}
