#!/usr/bin/env node
/*
 * link-samples — put the runnable app next to the recipe that explains it.
 *
 * The problem this solves: a cookbook page explains a pattern, and 152 working
 * apps demonstrate it, and until now the only connection between the two was a
 * link to the ROOT of abap2UI5/samples. A reader who follows it lands in a
 * repository of 300 files named z2ui5_cl_smp_app_<number> - the class name
 * encodes nothing - and has to guess. Meanwhile an AI agent can query the same
 * catalogue by keyword (abap2UI5/mcp-server, the `examples` tool). The human had
 * the worse deal.
 *
 * How it works, and why it is generated rather than written by hand:
 *
 *   A page DECLARES its samples in frontmatter, by class name only:
 *
 *     ---
 *     outline: [2, 4]
 *     samples:
 *       - z2ui5_cl_smp_app_009
 *       - z2ui5_cl_smp_app_078
 *     ---
 *
 *   Everything else - the title, the folder, the URL - is read from the
 *   catalogue of the repository the class belongs to, which is itself
 *   generated from the classes' abapGit short texts. So a sample that gets
 *   renamed, re-described or moved between packages updates here on the next
 *   run, and a sample that is DELETED fails this script instead of leaving a
 *   404 on the documentation site.
 *
 *   THE CLASS PREFIX DECIDES THE REPOSITORY. `z2ui5_cl_smp_app_*` is
 *   abap2UI5/samples, `z2ui5_cl_smpc_*` abap2UI5/samples-controls,
 *   `z2ui5_cl_smps_*` abap2UI5/samples-stack - the three prefixes are disjoint
 *   by the family's own naming rule, and no number means anything without one.
 *   Until 2026-09 only the first repository could be declared: the blob link
 *   was hardcoded to it, and 668 samples of the other two - every control
 *   port, every RAP, OData and WebSocket sample - were out of reach of the
 *   pages that explain exactly them. The samples repository is read from its
 *   SAMPLES.md as before; the other two from their catalogue.json
 *   (lib/catalogue.mjs knows where each one is).
 *
 *   Nothing about a sample is retyped in this repository. The one thing a page
 *   states is which samples are relevant, which is the one thing the catalogue
 *   cannot know.
 *
 * The block is written between markers at the end of the page and committed,
 * so building the site needs no samples checkout - only regenerating does.
 *
 * The reverse direction is checked too: a class of abap2UI5/samples this
 * documentation links to has to carry a `" @docs` line naming the page.
 * Somebody who arrives in the samples repository from a search engine sees
 * the chapter that explains what they are reading, and a page rename cannot
 * silently orphan it. The other two repositories carry no such line by their
 * own convention (samples-stack's AGENTS.md: the pairing is declared on the
 * documentation side); for a class of theirs the check is that it is in the
 * repository's catalogue and, when a checkout is at hand, in its tree.
 *
 *   node scripts/link-samples.mjs            rewrite the blocks
 *   node scripts/link-samples.mjs --check    fail if a rewrite would change
 *                                            anything (this is what CI runs)
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { parseCatalogue, entriesByClass, loadCatalogue, resolveHome } from './lib/catalogue.mjs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const DOCS = path.join(ROOT, 'docs');
const CHECK = process.argv.includes('--check');

/* The three repositories a page may declare a class from, in the order the
 * family numbers them. `blob` is where a row links; `backlinks` says whether
 * the classes over there carry a `" @docs` line this script holds them to. */
const REPOS = {
  samples: { blob: 'https://github.com/abap2UI5/samples/blob/main', backlinks: true },
  'samples-controls': { blob: 'https://github.com/abap2UI5/samples-controls/blob/main', backlinks: false },
  'samples-stack': { blob: 'https://github.com/abap2UI5/samples-stack/blob/main', backlinks: false },
};
// how a class's `" @docs` line spells a page of this site
const SITE = 'https://abap2ui5.github.io/docs/';
const START = '<!-- samples:start (generated by scripts/link-samples.mjs — do not edit) -->';
const END = '<!-- samples:end -->';

/** Which repository a declared class belongs to - by its prefix, the one
 *  thing about a sample's name that carries meaning (AGENTS.md of every
 *  sample repository: numbers are per repository and reused freely). */
function repoOf(cls) {
  const c = cls.toLowerCase();
  if (c.startsWith('z2ui5_cl_smpc_')) return 'samples-controls';
  if (c.startsWith('z2ui5_cl_smps_')) return 'samples-stack';
  return 'samples';
}

/* ------------------------------------------------------------------ input */

/** The samples checkout: an explicit path, or a sibling under any of the
 *  directory names the repository has been cloned as. */
function resolveSamples() {
  const candidates = [
    process.env.SAMPLES_HOME,
    path.join(ROOT, '.samples'),
    path.join(ROOT, '..', 'samples'),
    path.join(ROOT, '..', 'abap2UI5-samples'),
  ].filter(Boolean);
  for (const dir of candidates) {
    if (fs.existsSync(path.join(dir, 'SAMPLES.md'))) return dir;
  }
  return null;
}

/* ------------------------------------------------------------------- pages */

/** The `samples:` key of a page's frontmatter. Block list or inline array —
 *  no YAML parser, because this is the only key anything here reads. */
function declaredSamples(text) {
  const fm = /^---\r?\n([\s\S]*?)\r?\n---/.exec(text);
  if (!fm) return [];
  const inline = /^samples:\s*\[(.*)\]\s*$/m.exec(fm[1]);
  if (inline) {
    return inline[1].split(',').map((s) => s.trim().replace(/^["']|["']$/g, '')).filter(Boolean);
  }
  const block = /^samples:\s*\r?\n((?:\s*-\s*.+\r?\n?)+)/m.exec(fm[1]);
  if (!block) return [];
  return block[1]
    .split(/\r?\n/)
    .map((l) => /^\s*-\s*(.+?)\s*$/.exec(l))
    .filter(Boolean)
    .map((m) => m[1].replace(/^["']|["']$/g, ''));
}

/** The page as `" @docs` names it: repository path under docs/, no suffix. */
function docsPath(file) {
  return path.relative(DOCS, file).replace(/\\/g, '/').replace(/\.md$/, '');
}

/** One row: the sample's label, then the class linked at its source. A class
 *  outside abap2UI5/samples says which repository it is in - and, for a
 *  samples-stack package that ships on a branch of its own, which branch -
 *  because that is what the reader pulls. */
function renderRow(e) {
  const link = `[\`${e.cls.toUpperCase()}\`](${REPOS[e.repo].blob}/${e.path})`;
  const where = e.repo === 'samples'
    ? ''
    : ` · [${e.repo}](https://github.com/abap2UI5/${e.repo})${e.branch ? `, branch \`${e.branch}\`` : ''}`;
  return `| ${e.label} | ${link}${where} |`;
}

function renderBlock(entries) {
  const rows = entries.map(renderRow).join('\n');
  return [
    START,
    '',
    '## Working Samples',
    '',
    'Complete apps from the [sample catalog](https://abap2ui5.github.io/playground/samples/)',
    'that use what this page describes. Each is a single class in [abap2UI5/samples](https://github.com/abap2UI5/samples)',
    'unless its row names another of the three sample repositories — pull that repository with',
    '[abapGit](https://abapgit.org) and start the class with `?app_start=<class>`.',
    '',
    '| Sample | Class |',
    '|---|---|',
    rows,
    '',
    END,
  ].join('\n');
}

/** Replace the marked block, or append one when the page has none yet. */
function withBlock(text, block) {
  const from = text.indexOf(START);
  if (from === -1) return `${text.replace(/\s*$/, '')}\n\n${block}\n`;
  const to = text.indexOf(END, from);
  if (to === -1) throw new Error('a page opens the samples block and never closes it');
  return text.slice(0, from) + block + text.slice(to + END.length);
}

/* -------------------------------------------------------------------- run */

function markdownFiles(dir, out = []) {
  for (const name of fs.readdirSync(dir)) {
    if (name === '.vitepress' || name === 'public' || name === 'node_modules') continue;
    const full = path.join(dir, name);
    if (fs.statSync(full).isDirectory()) markdownFiles(full, out);
    else if (full.endsWith('.md')) out.push(full);
  }
  return out;
}

const samplesHome = resolveSamples();
if (!samplesHome) {
  // Not an error: the committed blocks are what the site builds from, so this
  // only has to run where the catalogue is at hand.
  console.log('no samples checkout found (set SAMPLES_HOME, or clone abap2UI5/samples as a');
  console.log('sibling) — the generated blocks in the pages are left as they are.');
  console.log(CHECK ? 'SKIPPED: nothing was verified.' : 'SKIPPED: nothing was written.');
  process.exit(0);
}

const catalogue = parseCatalogue(fs.readFileSync(path.join(samplesHome, 'SAMPLES.md'), 'utf8'));
if (catalogue.size === 0) throw new Error(`no rows parsed out of ${samplesHome}/SAMPLES.md`);

/* The other two repositories: their catalogue.json, from a checkout when one
 * is here (CI checks all three out) and from the published copy otherwise -
 * lib/catalogue.mjs's fallback chain. A checkout is what lets the class's
 * file be looked for; a published catalogue only says the class exists.
 * Neither is required: a page that declares none of their classes needs
 * neither, and a page that does is told when its class cannot be verified. */
const homes = { samples: samplesHome };
const catalogues = { samples: catalogue };
for (const repo of ['samples-controls', 'samples-stack']) {
  homes[repo] = resolveHome(repo, ROOT);
  const loaded = await loadCatalogue(repo, ROOT);
  catalogues[repo] = loaded ? entriesByClass(loaded.catalogue) : null;
  if (!loaded) console.log(`no ${repo} catalogue at hand (checkout or network) - its classes cannot be verified`);
}

/** The pages a sample class points at, as paths under docs/. */
function backlinks(relSource) {
  const file = path.join(samplesHome, relSource);
  if (!fs.existsSync(file)) return [];
  const line = (fs.readFileSync(file, 'utf8').match(/^" @docs (.+?)\r?$/m) || [, ''])[1].trim();
  return line.split(/\s+/).filter(Boolean).map((u) => u.replace(SITE, ''));
}

const problems = [];
let pages = 0;
let links = 0;
let written = 0;
let handwritten = 0;
let handwrittenGone = 0;

for (const file of markdownFiles(DOCS)) {
  const text = fs.readFileSync(file, 'utf8');
  const declared = declaredSamples(text);
  if (declared.length === 0) {
    if (text.includes(START)) {
      problems.push(`${docsPath(file)}: has a generated samples block but declares no \`samples:\``);
    }
    continue;
  }
  pages += 1;

  const entries = [];
  for (const cls of declared) {
    const repo = repoOf(cls);
    const rows = catalogues[repo];
    if (!rows) {
      const home = repo === 'samples-stack' ? 'SAMPLES_STACK_HOME' : 'SAMPLES_CONTROLS_HOME';
      problems.push(`${docsPath(file)}: \`${cls}\` is a ${repo} class and that catalogue is not at hand — clone abap2UI5/${repo} as a sibling or set ${home}`);
      continue;
    }
    const hit = rows.get(cls.toLowerCase());
    if (!hit) {
      problems.push(`${docsPath(file)}: \`${cls}\` is not in the ${repo} catalogue — renamed, deleted, or a typo`);
      continue;
    }
    entries.push({ cls, repo, ...hit });

    if (REPOS[repo].backlinks) {
      // the way back: the class has to name this page
      if (!backlinks(hit.path).includes(docsPath(file))) {
        problems.push(
          `${hit.path}: does not point back at ${docsPath(file)}\n`
          + `    add \`${SITE}${docsPath(file)}\` to the class's \`" @docs\` line in abap2UI5/samples`,
        );
      }
    } else if (homes[repo] && !fs.existsSync(path.join(homes[repo], hit.path))) {
      // no line to hold the class to over there, so the file itself is held:
      // the catalogue says where it is, and the tree has to agree
      problems.push(`${docsPath(file)}: \`${cls}\` is in the ${repo} catalogue at ${hit.path}, which is not in the checkout at ${homes[repo]}`);
    }
  }
  links += entries.length;

  const next = withBlock(text, renderBlock(entries));
  if (next === text) continue;
  if (CHECK) {
    problems.push(`${docsPath(file)}: the generated samples block is out of date — run \`npm run link:samples\``);
  } else {
    fs.writeFileSync(file, next);
    written += 1;
  }
}

/* And the links a page writes BY HAND, which are the hole in the promise this
 * script's header makes. The generated block exists so that "a sample that is
 * DELETED fails this script instead of leaving a 404 on the documentation
 * site" - but that only covers the classes a page DECLARES. A sentence in the
 * prose can name a sample the same way, straight at its source file:
 *
 *     see [sample 009](https://github.com/abap2UI5/samples/blob/main/src/01/z2ui5_cl_smp_app_009.clas.abap)
 *
 * and 97 distinct paths across 164 links are written that way. Nothing looked
 * at them. The samples repository RENUMBERS - its classes are named by number
 * and the generators close gaps - so a link like that is one renumber away
 * from a 404, and the reader is the one who finds out.
 *
 * check-api-names asks exactly this question for abap2UI5/abap2UI5, and it
 * asks it over the network, one HEAD per path. Here the whole checkout is
 * already open (CI clones it in full for the catalogue), so the answer is a
 * file lookup: no request, and it fails on a path that moved as readily as on
 * one that was deleted. The other two repositories are held the same way
 * wherever their tree is here; a published catalogue cannot answer for a
 * README or a folder link, so without a checkout their links pass unread.
 *
 * The generated blocks are skipped - they are written FROM the catalogue, so
 * checking them would only be checking this script against itself, and the
 * declared-samples loop above already fails on a class the catalogue lost. */
{
  const seen = new Map();   // "<repo>/<path>" -> pages that link it
  for (const file of markdownFiles(DOCS)) {
    let text = fs.readFileSync(file, 'utf8');
    const from = text.indexOf(START);
    if (from !== -1) {
      const to = text.indexOf(END, from);
      text = to === -1 ? text.slice(0, from) : text.slice(0, from) + text.slice(to);
    }
    for (const m of text.matchAll(/https:\/\/github\.com\/abap2UI5\/(samples(?:-controls|-stack)?)\/blob\/main\/([^)`"\s>]+)/g)) {
      const target = `${m[1]}/${m[2].split('#')[0].replace(/[.,;:)]+$/, '')}`;
      if (!seen.has(target)) seen.set(target, new Set());
      seen.get(target).add(docsPath(file));
    }
  }
  handwritten = seen.size;
  for (const [target, onPages] of seen) {
    const slash = target.indexOf('/');
    const repo = target.slice(0, slash);
    const rel = target.slice(slash + 1);
    if (!homes[repo]) continue;
    if (fs.existsSync(path.join(homes[repo], rel))) continue;
    handwrittenGone += 1;
    problems.push(
      `${[...onPages].sort().join(', ')}: links ${rel} in abap2UI5/${repo}, which is not there on main\n`
      + '    renumbered, moved or deleted - a link every reader who clicks it gets a 404 from',
    );
  }
}

/* And the sweep the other way round, over the WHOLE catalogue rather than only
 * the classes some page happens to declare. Without it, renaming a page here
 * leaves the samples repository pointing at a 404 and nothing notices: the page
 * that used to declare the sample is gone, so the check above never looks at
 * it. This is the case a cross-repository link actually fails in. */
for (const [cls, hit] of catalogue) {
  for (const page of backlinks(hit.path)) {
    if (fs.existsSync(path.join(DOCS, `${page}.md`))) continue;
    problems.push(
      `${hit.path}: \`" @docs\` points at ${page}, which is not a page here\n`
      + `    a renamed or deleted page — fix the class in abap2UI5/samples (${cls})`,
    );
  }
}

const where = (repo) => (homes[repo] ? path.relative(ROOT, homes[repo]) || homes[repo] : 'published catalogue');
console.log(`${catalogue.size} samples in the catalogue (${where('samples')})`
  + ['samples-controls', 'samples-stack']
    .filter((repo) => catalogues[repo])
    .map((repo) => `, ${catalogues[repo].size} in ${repo} (${where(repo)})`).join(''));
console.log(`${pages} page(s) declare ${links} sample link(s)${CHECK ? '' : `, ${written} rewritten`}`);
console.log(`${handwritten} source path(s) linked by hand in the prose`
  + (handwrittenGone ? `, ${handwrittenGone} of them gone` : ', all present in the checkout'));

if (problems.length) {
  console.error(`\n${problems.length} problem(s):`);
  for (const p of problems) console.error(`  ${p}`);
  process.exit(1);
}
console.log(CHECK ? 'up to date.' : 'done.');
