#!/usr/bin/env node
/*
 * link-samples — put the runnable app next to the recipe that explains it.
 *
 * The problem this solves: a cookbook page explains a pattern, and 152 working
 * apps demonstrate it, and until now the only connection between the two was a
 * link to the ROOT of abap2UI5/samples. A reader who follows it lands in a
 * repository of 300 files named z2ui5_cl_smp_app_<number> - the class name
 * encodes nothing - and has to guess. Meanwhile an AI agent can query the same
 * catalogue by keyword (abap2UI5/ai-mcp, the `examples` tool). The human had
 * the worse deal.
 *
 * How it works, and why it is generated rather than written by hand:
 *
 *   A page DECLARES its samples in frontmatter, by class name only:
 *
 *     ---
 *     outline: [2, 4]
 *     samples:
 *       - z2ui5_cl_smp_app_009
 *       - z2ui5_cl_smp_app_078
 *     ---
 *
 *   Everything else - the title, the folder, the URL - is read from the
 *   catalogue (SAMPLES.md in a samples checkout), which is itself generated
 *   from the classes' abapGit short texts. So a sample that gets renamed,
 *   re-described or moved between packages updates here on the next run, and a
 *   sample that is DELETED fails this script instead of leaving a 404 on the
 *   documentation site.
 *
 *   Nothing about a sample is retyped in this repository. The one thing a page
 *   states is which samples are relevant, which is the one thing the catalogue
 *   cannot know.
 *
 * The block is written between markers at the end of the page and committed,
 * so building the site needs no samples checkout - only regenerating does.
 *
 * The reverse direction is checked too: a class this documentation links to
 * has to carry a `" @docs` line naming the page. Somebody who arrives in the
 * samples repository from a search engine sees the chapter that explains what
 * they are reading, and a page rename cannot silently orphan it.
 *
 *   node scripts/link-samples.mjs            rewrite the blocks
 *   node scripts/link-samples.mjs --check    fail if a rewrite would change
 *                                            anything (this is what CI runs)
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { parseCatalogue } from './lib/catalogue.mjs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const DOCS = path.join(ROOT, 'docs');
const CHECK = process.argv.includes('--check');

const BLOB = 'https://github.com/abap2UI5/samples/blob/main';
// how a class's `" @docs` line spells a page of this site
const SITE = 'https://abap2ui5.github.io/docs/';
const START = '<!-- samples:start (generated by scripts/link-samples.mjs — do not edit) -->';
const END = '<!-- samples:end -->';

/* ------------------------------------------------------------------ input */

/** The samples checkout: an explicit path, or a sibling under any of the
 *  directory names the repository has been cloned as. */
function resolveSamples() {
  const candidates = [
    process.env.SAMPLES_HOME,
    path.join(ROOT, '.samples'),
    path.join(ROOT, '..', 'samples'),
    path.join(ROOT, '..', 'abap2UI5-samples'),
  ].filter(Boolean);
  for (const dir of candidates) {
    if (fs.existsSync(path.join(dir, 'SAMPLES.md'))) return dir;
  }
  return null;
}

/* ------------------------------------------------------------------- pages */

/** The `samples:` key of a page's frontmatter. Block list or inline array —
 *  no YAML parser, because this is the only key anything here reads. */
function declaredSamples(text) {
  const fm = /^---\r?\n([\s\S]*?)\r?\n---/.exec(text);
  if (!fm) return [];
  const inline = /^samples:\s*\[(.*)\]\s*$/m.exec(fm[1]);
  if (inline) {
    return inline[1].split(',').map((s) => s.trim().replace(/^["']|["']$/g, '')).filter(Boolean);
  }
  const block = /^samples:\s*\r?\n((?:\s*-\s*.+\r?\n?)+)/m.exec(fm[1]);
  if (!block) return [];
  return block[1]
    .split(/\r?\n/)
    .map((l) => /^\s*-\s*(.+?)\s*$/.exec(l))
    .filter(Boolean)
    .map((m) => m[1].replace(/^["']|["']$/g, ''));
}

/** The page as `" @docs` names it: repository path under docs/, no suffix. */
function docsPath(file) {
  return path.relative(DOCS, file).replace(/\\/g, '/').replace(/\.md$/, '');
}

function renderBlock(entries) {
  const rows = entries
    .map((e) => `| ${e.label} | [\`${e.cls.toUpperCase()}\`](${BLOB}/${e.path}) |`)
    .join('\n');
  return [
    START,
    '',
    '## Working Samples',
    '',
    'Complete apps from the [sample catalogue](https://github.com/abap2UI5/samples/blob/main/SAMPLES.md)',
    'that use what this page describes. Each is a single class — pull the repository with',
    '[abapGit](https://abapgit.org) and start it with `?app_start=<class>`.',
    '',
    '| Sample | Class |',
    '|---|---|',
    rows,
    '',
    END,
  ].join('\n');
}

/** Replace the marked block, or append one when the page has none yet. */
function withBlock(text, block) {
  const from = text.indexOf(START);
  if (from === -1) return `${text.replace(/\s*$/, '')}\n\n${block}\n`;
  const to = text.indexOf(END, from);
  if (to === -1) throw new Error('a page opens the samples block and never closes it');
  return text.slice(0, from) + block + text.slice(to + END.length);
}

/* -------------------------------------------------------------------- run */

function markdownFiles(dir, out = []) {
  for (const name of fs.readdirSync(dir)) {
    if (name === '.vitepress' || name === 'public' || name === 'node_modules') continue;
    const full = path.join(dir, name);
    if (fs.statSync(full).isDirectory()) markdownFiles(full, out);
    else if (full.endsWith('.md')) out.push(full);
  }
  return out;
}

const samplesHome = resolveSamples();
if (!samplesHome) {
  // Not an error: the committed blocks are what the site builds from, so this
  // only has to run where the catalogue is at hand.
  console.log('no samples checkout found (set SAMPLES_HOME, or clone abap2UI5/samples as a');
  console.log('sibling) — the generated blocks in the pages are left as they are.');
  console.log(CHECK ? 'SKIPPED: nothing was verified.' : 'SKIPPED: nothing was written.');
  process.exit(0);
}

const catalogue = parseCatalogue(fs.readFileSync(path.join(samplesHome, 'SAMPLES.md'), 'utf8'));
if (catalogue.size === 0) throw new Error(`no rows parsed out of ${samplesHome}/SAMPLES.md`);

/** The pages a sample class points at, as paths under docs/. */
function backlinks(relSource) {
  const file = path.join(samplesHome, relSource);
  if (!fs.existsSync(file)) return [];
  const line = (fs.readFileSync(file, 'utf8').match(/^" @docs (.+?)\r?$/m) || [, ''])[1].trim();
  return line.split(/\s+/).filter(Boolean).map((u) => u.replace(SITE, ''));
}

const problems = [];
let pages = 0;
let links = 0;
let written = 0;

for (const file of markdownFiles(DOCS)) {
  const text = fs.readFileSync(file, 'utf8');
  const declared = declaredSamples(text);
  if (declared.length === 0) {
    if (text.includes(START)) {
      problems.push(`${docsPath(file)}: has a generated samples block but declares no \`samples:\``);
    }
    continue;
  }
  pages += 1;

  const entries = [];
  for (const cls of declared) {
    const hit = catalogue.get(cls.toLowerCase());
    if (!hit) {
      problems.push(`${docsPath(file)}: \`${cls}\` is not in the sample catalogue — renamed, deleted, or a typo`);
      continue;
    }
    entries.push({ cls, ...hit });

    // the way back: the class has to name this page
    if (!backlinks(hit.path).includes(docsPath(file))) {
      problems.push(
        `${hit.path}: does not point back at ${docsPath(file)}\n`
        + `    add \`${SITE}${docsPath(file)}\` to the class's \`" @docs\` line in abap2UI5/samples`,
      );
    }
  }
  links += entries.length;

  const next = withBlock(text, renderBlock(entries));
  if (next === text) continue;
  if (CHECK) {
    problems.push(`${docsPath(file)}: the generated samples block is out of date — run \`npm run link:samples\``);
  } else {
    fs.writeFileSync(file, next);
    written += 1;
  }
}

/* And the sweep the other way round, over the WHOLE catalogue rather than only
 * the classes some page happens to declare. Without it, renaming a page here
 * leaves the samples repository pointing at a 404 and nothing notices: the page
 * that used to declare the sample is gone, so the check above never looks at
 * it. This is the case a cross-repository link actually fails in. */
for (const [cls, hit] of catalogue) {
  for (const page of backlinks(hit.path)) {
    if (fs.existsSync(path.join(DOCS, `${page}.md`))) continue;
    problems.push(
      `${hit.path}: \`" @docs\` points at ${page}, which is not a page here\n`
      + `    a renamed or deleted page — fix the class in abap2UI5/samples (${cls})`,
    );
  }
}

console.log(`${catalogue.size} samples in the catalogue (${path.relative(ROOT, samplesHome) || samplesHome})`);
console.log(`${pages} page(s) declare ${links} sample link(s)${CHECK ? '' : `, ${written} rewritten`}`);

if (problems.length) {
  console.error(`\n${problems.length} problem(s):`);
  for (const p of problems) console.error(`  ${p}`);
  process.exit(1);
}
console.log(CHECK ? 'up to date.' : 'done.');
